spring:
  profiles:
    active: pre
  application:
    name: @artifactId@
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yml
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        prefix: ${spring.application.name}
        import-check:
          enabled: false
        shared-configs:
          - data-id: common.yml
            group: DEFAULT_GROUP
            refresh: true
        enabled: false
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:public}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        enabled: false
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:common.yml

  # ✅ 数据源配置移动到正确的位置
  datasource:
    initialize: false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATASOURCE_HOST:127.0.0.1:3306}/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATASOURCE_USER_NAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1
      test-on-borrow: true

  # ✅ Redis 配置也移动到正确的位置
  redis:
    host: ${REDIS_HOST:172.16.0.93}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:OB805j835I46}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

server:
  port: ${SERVER_PORT:8080}

# MyBatis 配置（只保留 MyBatis 相关配置）
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.test.**.entity
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  config: classpath:logback.xml
  level:
    com.alibaba: WARN
    org.apache.dubbo: WARN
    org.springframework: INFO
    org.mybatis: DEBUG

debug: false